# embed_assets.cmake — read static assets and emit a generated C++ source
# that exposes them as `std::string_view` constants. Hex-encoding side-steps
# any raw-string-delimiter collisions (index.html contains JS with random
# punctuation).
#
# Inputs (set in caller scope):
#   ASSETS_DIR  — directory holding index.html, style.css, logo.svg
#   OUT_FILE    — generated .cpp path
#
# The generated file populates `onebit::landing::assets::{INDEX_HTML,
# STYLE_CSS, LOGO_SVG}` byte arrays + matching `std::string_view`s.

function(embed_one var path out_var)
    file(READ "${path}" content HEX)
    string(LENGTH "${content}" hex_len)
    math(EXPR byte_len "${hex_len} / 2")
    set(bytes "")
    set(idx 0)
    while(idx LESS hex_len)
        string(SUBSTRING "${content}" ${idx} 2 b)
        if(NOT bytes STREQUAL "")
            string(APPEND bytes ",")
        endif()
        string(APPEND bytes "0x${b}")
        math(EXPR idx "${idx} + 2")
    endwhile()
    set(${var}_BYTES "${bytes}" PARENT_SCOPE)
    set(${var}_LEN   "${byte_len}" PARENT_SCOPE)
endfunction()

embed_one(INDEX "${ASSETS_DIR}/index.html" _)
embed_one(STYLE "${ASSETS_DIR}/style.css"  _)
embed_one(LOGO  "${ASSETS_DIR}/logo.svg"   _)

file(WRITE "${OUT_FILE}"
"// AUTO-GENERATED by cpp/landing/cmake/embed_assets.cmake — DO NOT EDIT.\n"
"#include \"onebit/landing/assets.hpp\"\n"
"\n"
"namespace onebit::landing::assets {\n"
"\n"
"namespace {\n"
"constexpr unsigned char kIndexHtmlBytes[] = { ${INDEX_BYTES} };\n"
"constexpr unsigned char kStyleCssBytes[]  = { ${STYLE_BYTES} };\n"
"constexpr unsigned char kLogoSvgBytes[]   = { ${LOGO_BYTES} };\n"
"} // namespace\n"
"\n"
"const std::string_view INDEX_HTML{ reinterpret_cast<const char*>(kIndexHtmlBytes), ${INDEX_LEN} };\n"
"const std::string_view STYLE_CSS { reinterpret_cast<const char*>(kStyleCssBytes),  ${STYLE_LEN} };\n"
"const std::string_view LOGO_SVG  { reinterpret_cast<const char*>(kLogoSvgBytes),   ${LOGO_LEN} };\n"
"\n"
"} // namespace onebit::landing::assets\n"
)
