#!/usr/bin/env bash
# strixhalo/discord/restore.sh — idempotent Discord integration restore.
#
# Reads:
#   strixhalo/discord/config.toml  — canonical channel + tag state
#   ~/.config/1bit/discord-secrets.env — bot tokens (chmod 600, NEVER committed)
#
# Writes:
#   ~/.config/systemd/user/strix-watch-discord.service.d/token.conf
#
# Runs:
#   1bit-helpdesk-setup  against the help-desk channel id
#   systemctl --user daemon-reload
#   systemctl --user restart strix-watch-discord.service
#
# Safe to run repeatedly — everything it does is idempotent.

set -euo pipefail

# fish shell (this box's default) doesn't export ~/.cargo/bin into the
# environment seen by bash; add it explicitly so `1bit-helpdesk-setup`
# and `1bit-watch-discord` resolve regardless of invocation context.
export PATH="$HOME/.cargo/bin:${PATH:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/config.toml"
SECRETS="$HOME/.config/1bit/discord-secrets.env"
DROPIN_DIR="$HOME/.config/systemd/user/strix-watch-discord.service.d"
DROPIN="$DROPIN_DIR/token.conf"

info()  { printf '\033[1;34m[info]\033[0m  %s\n' "$*"; }
warn()  { printf '\033[1;33m[warn]\033[0m  %s\n' "$*" >&2; }
fatal() { printf '\033[1;31m[fail]\033[0m  %s\n' "$*" >&2; exit 1; }

[[ -f "$CONFIG" ]]  || fatal "missing $CONFIG"
[[ -f "$SECRETS" ]] || fatal "missing $SECRETS — create it with DISCORD_BOT_TOKEN and ECHO_BOT_TOKEN"
command -v 1bit-helpdesk-setup >/dev/null \
    || fatal "1bit-helpdesk-setup not on PATH — cargo install --path crates/1bit-agents --bin 1bit-helpdesk-setup"
command -v 1bit-watch-discord >/dev/null \
    || warn  "1bit-watch-discord not on PATH — install it before the systemd restart will work"

# Pull the help-desk channel id out of config.toml without needing a full
# TOML parser. The line shape is fixed by config.toml's formatter.
HELP_DESK_ID="$(awk -F'"' '/^help_desk[[:space:]]*=.*id[[:space:]]*=/ {print $2; exit}' "$CONFIG")"
[[ -n "$HELP_DESK_ID" ]] || fatal "could not parse channels.help_desk.id from $CONFIG"

# Optional: guild_id and member_role_id. Empty strings are fine — they
# map to "global slash registration" and "auto-role disabled" respectively.
GUILD_ID="$(awk -F'"' '/^id[[:space:]]*=/{if(!seen){print $2; seen=1}}' "$CONFIG")"
MEMBER_ROLE_ID="$(awk -F'"' '/^member_role_id[[:space:]]*=/ {print $2; exit}' "$CONFIG")"

info "help-desk channel id: $HELP_DESK_ID"
info "guild id: ${GUILD_ID:-<unset>}"
info "member role id: ${MEMBER_ROLE_ID:-<unset — auto-role disabled>}"

# Load secrets into the current shell without echoing to terminal.
set -a
# shellcheck disable=SC1090
source "$SECRETS"
set +a

[[ -n "${DISCORD_BOT_TOKEN:-}" ]] || fatal "DISCORD_BOT_TOKEN missing from $SECRETS"
[[ -n "${ECHO_BOT_TOKEN:-}" ]]    || fatal "ECHO_BOT_TOKEN missing from $SECRETS"

info "writing systemd drop-in → $DROPIN"
mkdir -p "$DROPIN_DIR"
umask 077
cat > "$DROPIN" <<EOF
[Service]
# Auto-generated by strixhalo/discord/restore.sh on $(date -Iseconds).
# Edit config.toml or secrets.env + re-run restore.sh; don't hand-edit.
Environment="RUST_LOG=info,serenity_gateway=info,serenity::gateway=info,serenity::http=warn,tungstenite=warn,hyper=warn,reqwest=warn"
Environment="DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN"
Environment="ECHO_BOT_TOKEN=$ECHO_BOT_TOKEN"
Environment="HALO_DISCORD_CHANNELS="
Environment="HALO_HELP_DESK_CHANNEL_ID=$HELP_DESK_ID"
Environment="HALO_GUILD_ID=$GUILD_ID"
Environment="HALO_MEMBER_ROLE_ID=$MEMBER_ROLE_ID"
Environment="HALO_WIKI_DIR=$HOME/repos/1bit-halo-workspace/docs/wiki"
EOF
chmod 600 "$DROPIN"

info "applying canonical tags + topic to help-desk forum"
DISCORD_BOT_TOKEN="$DISCORD_BOT_TOKEN" \
CHANNEL_ID="$HELP_DESK_ID" \
    1bit-helpdesk-setup || warn "1bit-helpdesk-setup failed — channel may not be a forum yet (convert it in Discord UI, then re-run)"

info "reloading + restarting systemd unit"
systemctl --user daemon-reload
systemctl --user restart strix-watch-discord.service

sleep 2
if systemctl --user is-active strix-watch-discord.service >/dev/null; then
    info "strix-watch-discord.service is active"
else
    warn "strix-watch-discord.service is NOT active — check: journalctl --user -u strix-watch-discord.service -n 40"
    exit 1
fi

info "done."
